routes/admin.php
<?php

use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\TagController;
use Illuminate\Support\Facades\Route;

Route::get('', [HomeController::class, 'index'])->name('admin.home');
Route::resource('users', UserController::class)->only('index', 'edit', 'update')->names('admin.users');
Route::resource('categories', CategoryController::class)->names('admin.categories');
Route::resource('tags', TagController::class)->names('admin.tags');
Route::resource('posts', PostController::class)->names('admin.posts');

routes/web.php
<?php

use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Route;

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::get('/', [PostController::class, 'index'])->name('posts.index');
Route::get('posts/{post}', [PostController::class, 'show'])->name('posts.show');
Route::get('category/{category}', [PostController::class, 'category'])->name('posts.category');
Route::get('tag/{tag}', [PostController::class, 'tag'])->name('posts.tag');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Http/Livewire/Admin/PostsIndex.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Post;
use Livewire\Component;
use Livewire\WithPagination;


class PostsIndex extends Component
{
    use WithPagination;  //para usar la paginación con livwwire

    protected $paginationTheme = "bootstrap"; //para que livewire use los estilos de bootstrap en vez de tailwind
    
    public $search;

    public function updatingSearch() // Solo se activa cuando pa propiedad search cambia de valor
    {
        $this->resetPage();
    }

    public function render()
    {
        $posts = Post::where('user_id', auth()->user()->id)
                        ->where('name', 'LIKE', '%' . $this->search . '%')
                        ->latest('id')
                        ->paginate();
        
        return view('livewire.admin.posts-index', compact('posts'));
    }
}

app/Http/Livewire/Admin/UsersIndex.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;

class UsersIndex extends Component
{
    use WithPagination;  //para usar la paginación con livwwire

    protected $paginationTheme = "bootstrap"; //para que livewire use los estilos de bootstrap en vez de tailwind
    
    public $search;

    public function updatingSearch() // Solo se activa cuando la propiedad search cambia de valor
    {
        $this->resetPage();
    }
    
    public function render()
    {
        $users = User::where('name', 'LIKE', '%' . $this->search . '%')
                        ->orwhere('email', 'LIKE', '%' . $this->search . '%')
                        ->paginate();

        return view('livewire.admin.users-index', compact('users'));
    }
}

app/Http/Livewire/Navigation.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

use App\Models\Category;

class Navigation extends Component
{
    public function render()
    {
        $categorias = Category::all();

        return view('livewire.navigation', compact('categorias'));
    }
}

resources/views/livewire/admin/posts-index.blade.php
<div class=" card">
    <div class="card-header">
        {{-- Sincronizo el input con la propiedad search de PostIndex.php--}}
        <input wire:model = "search" class=" form-control" placeholder="Escriba el nombre de un post">
    </div>
    @if ($posts->count())
        <div class="card-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th colspan="2"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($posts as $post)
                        <tr>
                            <th>{{$post->id}}</th>
                            <th>{{$post->name}}</th>
                            <th width="10px"><a class=" btn btn-primary btn-sm" href="{{route('admin.posts.edit', $post)}}">Editar</a></th>
                            <th width="10px">
                                <form action="{{route('admin.posts.destroy', $post)}}" method="POST">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-danger btn-sm" type="submit">Eliminar</button>
                                </form>
                            </th>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        {{-- Aqui pongo la paginación--}}
        <div class="car-footer">
            {{$posts->links()}}
        </div>
    @else
        <div class="card-body">
            <strong>No hay ninguna coincidencia.</strong>
        </div>
    @endif
</div>

resources/views/livewire/admin/users-index.blade.php
<div>
    <div class="card">
        <div class="card-header">
            <input wire:model="search" class="form-control" placeholder="Ingrese el nombre o email de un usuario">
        </div>
        @if ($users->count())
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nombre</th>
                            <th>Email</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($users as $user)
                            <tr>
                                <th>{{$user->id}}</th>
                                <th>{{$user->name}}</th>
                                <th>{{$user->email}}</th>
                                <th width="10px">
                                    <a class="btn btn-primary" href="{{route('admin.users.edit', $user)}}">Editar</a>
                                </th>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                {{$users->links()}}
            </div>
        @else
            <div class="card-body">
                <strong>No hay coincidencias.</strong>
            </div>
        @endif

    </div>
</div>